### PR TITLE
Rework Default Generator MRO Logic

### PR DESCRIPTION
**Pull request by rmorshea**
The only thing odd about this approach to the default decorator is that the default handlers remain in `_trait_default_generators` even if they don't generate default values due to the `mro` logic. That seems unintuitive to me so I've reworked things slightly by putting the `mro` logic on the default handler's `instance_init` method so that it's only put in `_trait_default_generators` if it will actually be used to create a default value.

### CODE REVIEW

**Comment by rmorshea** [comment]
With the inclusion of this PR, I like your default decorator implementation much better than mine.

**Comment by rmorshea** [comment]
Forgot about the issue with the call to `_dynamic_default_callable` in `instance_init`...

**Comment by rmorshea** [comment]
making pull against upstream master

**Comment by SylvainCorlay** [comment]
@rmorshea nice, probably better on master indeed.

**Pull request closed without merging**
